# Generated by Django 4.1.7 on 2023-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KamarKost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idKamar', models.CharField(max_length=10)),
                ('TipeKamar', models.CharField(max_length=10)),
                ('Harga', models.CharField(max_length=6)),
                ('FasilitasKOst', models.CharField(max_length=250)),
                ('masaTenggang', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='penghuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdKamar', models.CharField(max_length=100)),
                ('NoTelepon', models.CharField(max_length=12)),
                ('ktp', models.CharField(max_length=16)),
            ],
        ),
    ]
