# Generated by Django 4.1.7 on 2023-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kamarkost_penghuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamarkost',
            name='gambar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='IdKamar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='NoTelp',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='kamarkost',
            name='idKamar',
            field=models.CharField(max_length=100),
        ),
    ]
