# Generated by Django 4.1.7 on 2023-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kamarkost_gambar_alter_admin_idkamar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkost',
            name='gambar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
