# Generated by Django 4.1.7 on 2023-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_kamarkost_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkost',
            name='gambar',
            field=models.ImageField(upload_to='kamar'),
        ),
    ]
