# Generated by Django 4.1.7 on 2023-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_kamarkost_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkost',
            name='gambar',
            field=models.ImageField(null=True, upload_to='static/img/kamar'),
        ),
    ]
