# Generated by Django 4.1.7 on 2023-04-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_kamarkost_namakost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Nama',
            new_name='user_name',
        ),
    ]
