# Generated by Django 4.1.7 on 2023-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_user_name_admin_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
