# Generated by Django 4.1.7 on 2023-04-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_admin_email_admin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Nama',
            new_name='user_name',
        ),
    ]
