# Generated by Django 4.1.7 on 2023-04-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
