# Generated by Django 4.1.7 on 2023-04-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
