# Generated by Django 4.1.7 on 2023-04-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='IdKamar',
        ),
    ]
