# Generated by Django 4.1.7 on 2023-04-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_kamarkost_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamarkost',
            name='nama',
        ),
    ]
