# Generated by Django 4.1.7 on 2023-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_kamarkost_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
