# Generated by Django 4.1.7 on 2023-05-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_kamarkost_kodeadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
