# Generated by Django 4.1.7 on 2023-05-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamarkost',
            name='statuskamar',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
