# Generated by Django 4.1.7 on 2023-05-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_kamarkost_statuskamar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamarkost',
            name='statuskamar',
        ),
    ]
