# Generated by Django 4.1.7 on 2023-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_kamarkost_statuskamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamarkost',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('occupied', 'Terisi'), ('under_repair', 'Dalam Perbaikan')], max_length=20, null=True),
        ),
    ]
