# Generated by Django 4.1.7 on 2023-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_kamarkost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkost',
            name='Harga',
            field=models.CharField(max_length=50),
        ),
    ]
