# Generated by Django 4.1.7 on 2023-05-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_kamarkost_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamarkost',
            name='status_kamar',
            field=models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], max_length=10, null=True),
        ),
    ]
