# Generated by Django 4.1.7 on 2023-05-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_kamarkost_status_kamar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamarkost',
            name='kodeadmin',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='app.admin'),
        ),
    ]
